package com.migestor.shared.usecase

import com.migestor.shared.domain.Student
import com.migestor.shared.domain.ImportResult

class StudentImporter {
    /**
     * Parses a CSV/TSV list of names.
     * Tries to find columns for first name and last name.
     */
    fun import(content: String): ImportResult {
        val candidates = parseCandidates(content)
        if (candidates.isEmpty()) {
            return ImportResult.Failure("No se encontraron alumnos válidos en el archivo.")
        }
        
        val students = candidates.map { 
            Student(
                id = 0, // ID will be generated by DB
                firstName = it.firstName,
                lastName = it.lastName,
                email = ""
            )
        }
        
        // In a real scenario, we might have warnings about duplicate names or missing data
        val warnings = mutableListOf<String>()
        if (candidates.any { it.firstName.isBlank() || it.lastName.isBlank() }) {
            warnings.add("Algunos alumnos tienen nombres o apellidos incompletos.")
        }

        return ImportResult.Success(students, warnings)
    }

    fun parseCandidates(content: String): List<StudentCandidate> {
        val lines = content.lines()
            .map { it.trim() }
            .filter { it.isNotEmpty() }
        
        if (lines.isEmpty()) return emptyList()

        val results = mutableListOf<StudentCandidate>()
        
        // Detect separator: Try ; , or \t
        val firstLine = lines.first()
        val separator = when {
            firstLine.contains("\t") -> "\t"
            firstLine.contains(";")  -> ";"
            firstLine.contains(",")  -> ","
            else -> " "
        }

        // Try to find header indices
        val header = lines.first().split(separator).map { it.trim().trim('"').lowercase() }
        val firstNameIdx = header.indexOfFirst { it.contains("nombre") || it.contains("name") || it == "n" }
        val lastNameIdx = header.indexOfFirst { it.contains("apellido") || it.contains("surname") || it == "a" }
        val fullNameIdx = header.indexOfFirst { it.contains("alumno") || it.contains("estudiante") || it.contains("full name") }

        val dataLines = if (firstNameIdx != -1 || lastNameIdx != -1 || fullNameIdx != -1) {
            lines.drop(1)
        } else {
            lines
        }

        for (line in dataLines) {
            // Skip common school header words
            if (line.contains("LISTADO", ignoreCase = true) || 
                line.contains("COLEGIO", ignoreCase = true) ||
                line.contains("CURSO", ignoreCase = true) ||
                line.contains("CLASE", ignoreCase = true)) {
                continue
            }

            val parts = line.split(separator).map { it.trim().trim('"') }
            
            val candidate = when {
                firstNameIdx != -1 && lastNameIdx != -1 -> {
                    val fn = parts.getOrNull(firstNameIdx) ?: ""
                    val ln = parts.getOrNull(lastNameIdx) ?: ""
                    if (fn.isBlank() && ln.isBlank()) null 
                    else StudentCandidate(fullName = if (ln.isNotBlank()) "$ln, $fn" else fn, firstName = fn, lastName = ln)
                }
                fullNameIdx != -1 -> {
                    val full = parts.getOrNull(fullNameIdx) ?: ""
                    if (full.isBlank()) null else StudentCandidate(full)
                }
                else -> {
                    // Optimized heuristic: try to find a meaningful name in the first 3 columns
                    val potentialName = parts.take(3).firstOrNull { it.any { c -> c.isLetter() } && it.length > 2 }
                    if (potentialName != null) StudentCandidate(potentialName) else null
                }
            }

            if (candidate != null) {
                results.add(candidate)
            }
        }
        
        return results
    }
}

data class StudentCandidate(
    val fullName: String,
    val firstName: String = extractFirstName(fullName),
    val lastName: String = extractLastName(fullName)
)

private fun extractFirstName(fullName: String): String {
    if (fullName.contains(",")) return fullName.substringAfter(",").trim()
    val parts = fullName.split(" ").filter { it.isNotBlank() }
    return if (parts.size > 1) parts.first() else fullName
}

private fun extractLastName(fullName: String): String {
    if (fullName.contains(",")) return fullName.substringBefore(",").trim()
    val parts = fullName.split(" ").filter { it.isNotBlank() }
    return if (parts.size > 1) parts.drop(1).joinToString(" ") else ""
}
